# Generated by Django 4.1.1 on 2022-09-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="topic",
        ),
        migrations.AddField(
            model_name="room",
            name="code",
            field=models.CharField(default="", max_length=8, unique=True),
        ),
    ]
