# Generated by Django 4.1.1 on 2022-09-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_room_code_room_aff_open_room_neg_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="code",
            field=models.CharField(default="", max_length=8, unique=True),
        ),
    ]
