# Generated by Django 4.1.1 on 2022-10-05 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0005_community_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="admins",
            field=models.ManyToManyField(
                related_name="communities", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
