# Generated by Django 4.1.1 on 2022-10-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_community_admins"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="currentPrompt",
            field=models.CharField(default="", max_length=255),
        ),
    ]
