# Generated by Django 3.2.5 on 2022-10-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_community_currentprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='communityName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
